[package]
name = "rust-sse-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.8.9", features = ["macros"] }
futures-util = { version = "*" }
tokio-stream = { version = "*" }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports", "async_tokio"] }

eventsource-client = "=0.17.5"
launchdarkly-sdk-transport = { version = "=0.1.4", features = ["hyper"] }

reqwest = { version = "0.13.4", default-features = false }
reqwest-sse = "*"

sse-reqwest-client = "0.4"

reqwest-eventsource = "0.6.0"
reqwest-old = { package = "reqwest", version = "=0.12.28", default-features = false }

sse-stream = "0.2.5"

sseer = { version = "0.3.0", features = ["reqwest"] }

eventsource-stream2 = "*"

trillium = "*"
trillium-client = { version = "*", features = ["sse"] }
trillium-tokio = "*"

rama = { version = "=0.4.0", features = ["http-full"] }

[[bench]]
name = "comparison"
harness = false
